[functions."search-nearby-eskilstuna"]
schedule = "*/20 * * * *"

[functions."search-nearby-linkoping"]
schedule = "*/10 * * * *"

[functions."search-nearby-nykoping"]
schedule = "*/15 * * * *"

[functions."search-nearby-stockholm"]
schedule = "*/5 * * * *"

[functions."search-norrkoping"]
schedule = "*/30 * * * *"
