[functions."search-nearby-eskilstuna"]
schedule = "*/5 * * * *"

[functions."search-nearby-linkoping"]
schedule = "*/5 * * * *"

[functions."search-nearby-nykoping"]
schedule = "*/5 * * * *"

[functions."search-nearby-stockholm"]
schedule = "*/5 * * * *"

[functions."search-norrkoping"]
schedule = "*/5 * * * *"
